const GET_POKEMONS = 'GET_POKEMONS'
const GET_POKEMON = 'GET_POKEMON'
const POST_POKEMON = 'POST_POKEMON'
const GET_TYPES = 'GET_TYPES'
const GET_FILTER = 'GET_FILTER'
const ORDER = 'ORDER'
const GET_ID = 'GET_ID'
const CREATED = 'CREATED'
const CLEAN = 'CLEAN'

module.exports = {
    GET_POKEMON,
    GET_POKEMONS,
    GET_TYPES,
    GET_FILTER,
    ORDER,
    GET_ID,
    CREATED,
    CLEAN,
    POST_POKEMON
}